travis:
  secure:
    BINSTAR_TOKEN: awozQt4qFMTPhWAYqOnYeUFBXjO/gheTBvKle1JFmyKFjFfo0hk1znNLlLqprL/n6LXjSgJQ46G++wL5S6T1m54KOpm1AyPAR9ELkLo522b2T6rH/4qaca+tPYVGKLeWJ4TSNU5LZme+DkN7QkYKqpk7Ls4bPSgaRYxtIYIEFPaIzHqXzIM+zcHO3ppPVB4tUYTSmAaSTEQoN7rYq2OytOXMgBZ0Mzo8vqHjxtdRudmCmZ6l+m6uwK/y4XSHCiEwq+kH9GvQ1BCZgnTBHentrFEhpByQUgjTJEuyD8tl+Thrd+oTuWHycsrj167yDS+/Wzgi0CjC7xp6Fv6PRqXdutzyv73XvvwE6sz+WMRwhbf0aDk4mzE1DocGwq6/mUMIPDnByM2VcJ1eEBGsRGTZaTxWCinm9XBeF3j9ZEgJei/VPDTuzy6zPcM7XKMzSjjgoAxHye7mYiDiIIZphK2YuTkmNorLtrhWYcNjtuBTMIGWrI0uz4bJ1NgxC2jAfYRE/o1GrlRA6hJVve/LjjgP+BcURklfe7HRZiJjn/rY3BxmZt9o0XD7N4AswXvXgYOQRehid44ICbP+CoSaAefl8gT8bO5uu//WlD7HVbgQ7JJBf/npySGLWzYNrH4iGKTOf5SBUHIaIvK0aiVURumrTq1zT8s91b+/5tRjL9HvEa4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
