travis:
  secure:
    BINSTAR_TOKEN: ZIEjS6O1LGrqCkjEk/rkwbQ8PgFgxd2ZSRnQxfG0i7qT80kgYcEFn/rXsIPGJYqgUJOFA2SMwUfIZ8PNCfqCsV+kQ54lzMRxysmkXD9aZm+MEdTQ0+EE8SAeABhcoMdyEFXOIZyrtYbiWtLEMVStbppYvXYNYKYWtw3ugCEh+A13ehNwhYvjmqONzSJL47tBbfeW8GmGOf3q0vaLs6kERztqLU2DHh3GeoB635pDKU0gmjYfFOtZQNqkLa7hzbVGj+HwDc0+YNLdUAb15TapwJ2PILRwrit0aLYMlfRENNNSL26zPE8Nb1+Er+xVy8He7t8CJEwzMh6EMhBh6uP6qVDgf0jaLbq8KuUIDWhdTewWKRhswadEGcD5QTWo9GZN8W6yID4vTF7I78H9Iyhl3IiQWe6+5ghvAge+hnQpAuJsmOV/3RG/6thPbZMdPN57EXgRZLDpAY5FrZ+khPBYhWReTcNRBbkeF7GpN5baFPoV8bYOVTfe2gf1dMcgyjX+6lirFuieh8bgk5R3SqR1m38JwjQob8hSklC4QmApS4BJl+20sAyrwl1etWUCT9mtZHLKp6/650x2OgS6cqcQOGssCpIv6RQtTYNcXRRk4SfShc3NXnlUq+YEXTgGmYbvSV31iq0OeaNVlPE8HKYPXsI1EJJ93PWjOWectHvz0kE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
